Models/ErrorViewModel.cs
namespace JM_Examen_P1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Montero.cs
namespace JM_Examen_P1.Models
{
    public class Montero
    {
        public int Id { get; set; }
        public int JM_SemestreId { get; set; }
        public double JM_Nota { get; set; }
        public string? JM_Nombre { get; set; }
        public bool JM_Estudiante { get; set; }
        public DateTime JM_Fecha { get; set; }
    }
}

Controllers/HomeController.cs
using JM_Examen_P1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace JM_Examen_P1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MonteroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JM_Examen_P1.Data;
using JM_Examen_P1.Models;

namespace JM_Examen_P1.Controllers
{
    public class MonteroesController : Controller
    {
        private readonly JM_Examen_P1Context _context;

        public MonteroesController(JM_Examen_P1Context context)
        {
            _context = context;
        }

        // GET: Monteroes
        public async Task<IActionResult> Index()
        {
              return _context.Montero != null ? 
                          View(await _context.Montero.ToListAsync()) :
                          Problem("Entity set 'JM_Examen_P1Context.Montero'  is null.");
        }

        // GET: Monteroes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Montero == null)
            {
                return NotFound();
            }

            var montero = await _context.Montero
                .FirstOrDefaultAsync(m => m.Id == id);
            if (montero == null)
            {
                return NotFound();
            }

            return View(montero);
        }

        // GET: Monteroes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Monteroes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,JM_SemestreId,JM_Nota,JM_Nombre,JM_Estudiante,JM_Fecha")] Montero montero)
        {
            if (ModelState.IsValid)
            {
                _context.Add(montero);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(montero);
        }

        // GET: Monteroes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Montero == null)
            {
                return NotFound();
            }

            var montero = await _context.Montero.FindAsync(id);
            if (montero == null)
            {
                return NotFound();
            }
            return View(montero);
        }

        // POST: Monteroes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,JM_SemestreId,JM_Nota,JM_Nombre,JM_Estudiante,JM_Fecha")] Montero montero)
        {
            if (id != montero.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(montero);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MonteroExists(montero.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(montero);
        }

        // GET: Monteroes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Montero == null)
            {
                return NotFound();
            }

            var montero = await _context.Montero
                .FirstOrDefaultAsync(m => m.Id == id);
            if (montero == null)
            {
                return NotFound();
            }

            return View(montero);
        }

        // POST: Monteroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Montero == null)
            {
                return Problem("Entity set 'JM_Examen_P1Context.Montero'  is null.");
            }
            var montero = await _context.Montero.FindAsync(id);
            if (montero != null)
            {
                _context.Montero.Remove(montero);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MonteroExists(int id)
        {
          return (_context.Montero?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Monteroes/Create.cshtml
@model JM_Examen_P1.Models.Montero

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Montero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="JM_SemestreId" class="control-label"></label>
                <input asp-for="JM_SemestreId" class="form-control" />
                <span asp-validation-for="JM_SemestreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JM_Nota" class="control-label"></label>
                <input asp-for="JM_Nota" class="form-control" />
                <span asp-validation-for="JM_Nota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JM_Nombre" class="control-label"></label>
                <input asp-for="JM_Nombre" class="form-control" />
                <span asp-validation-for="JM_Nombre" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="JM_Estudiante" /> @Html.DisplayNameFor(model => model.JM_Estudiante)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="JM_Fecha" class="control-label"></label>
                <input asp-for="JM_Fecha" class="form-control" />
                <span asp-validation-for="JM_Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Monteroes/Delete.cshtml
@model JM_Examen_P1.Models.Montero

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Montero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JM_SemestreId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JM_SemestreId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JM_Nota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JM_Nota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JM_Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JM_Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JM_Estudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JM_Estudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JM_Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JM_Fecha)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Monteroes/Details.cshtml
@model JM_Examen_P1.Models.Montero

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Montero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JM_SemestreId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JM_SemestreId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JM_Nota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JM_Nota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JM_Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JM_Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JM_Estudiante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JM_Estudiante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JM_Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JM_Fecha)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Monteroes/Edit.cshtml
@model JM_Examen_P1.Models.Montero

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Montero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="JM_SemestreId" class="control-label"></label>
                <input asp-for="JM_SemestreId" class="form-control" />
                <span asp-validation-for="JM_SemestreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JM_Nota" class="control-label"></label>
                <input asp-for="JM_Nota" class="form-control" />
                <span asp-validation-for="JM_Nota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JM_Nombre" class="control-label"></label>
                <input asp-for="JM_Nombre" class="form-control" />
                <span asp-validation-for="JM_Nombre" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="JM_Estudiante" /> @Html.DisplayNameFor(model => model.JM_Estudiante)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="JM_Fecha" class="control-label"></label>
                <input asp-for="JM_Fecha" class="form-control" />
                <span asp-validation-for="JM_Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Monteroes/Index.cshtml
@model IEnumerable<JM_Examen_P1.Models.Montero>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JM_SemestreId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JM_Nota)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JM_Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JM_Estudiante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JM_Fecha)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.JM_SemestreId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JM_Nota)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JM_Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JM_Estudiante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JM_Fecha)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JM_Examen_P1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JM_Examen_P1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JM_Instituto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Monteroes" asp-action="Index">JM_Formulario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - JM_Examen_P1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>